'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ExceptionsReportHistory

    '''<summary>
    '''myForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SelectPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectPeriod As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''SelectSociety control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectSociety As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''SelectPersonnelDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectPersonnelDivision As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As ICMTools.MasterPage
        Get
            Return CType(MyBase.Master, ICMTools.MasterPage)
        End Get
    End Property
End Class
