<%@ Page Title="Renegociaciones - CptRe-Negocia" Language="vb" AutoEventWireup="false" MasterPageFile="~/Master/MasterPage.Master" CodeBehind="RenegociacionesCptReNegocia.aspx.vb" Inherits="ICMTools.RenegociacionesCptReNegocia" Async="true" %>
<%@ MasterType VirtualPath="~/Master/MasterPage.Master" %>
<asp:Content ID="TopbarContent" ContentPlaceHolderID="TopbarContent" runat="server">
    <div class="d-flex gap-1"><a href="../Pages/RenegociacionesCptReNegocia.aspx" class="btn active btn-sm btn-bar d-flex flex-column align-items-center text-dark"><i class="fas fa-upload fa-2x"></i><small>Carga</small></a></div>
</asp:Content>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server">
    <meta name="description" content="Carga de renegociaciones CptRe-Negocia" /><title>Renegociaciones - CptRe-Negocia</title>
    <script src="../Scripts/jquery.min.js"></script>
    <script type="text/javascript">
        const configuraciones = { servidor: { userEmail: "", serverPath: "", maxFileSize: "" }, page: "Renegociaciones", carga: { periodSelector: "#SelectPeriod", regionSelector: "#SelectRegion", fileType: "Renegociaciones", extension: ".xlsx", fileClass: "ICMTools.RenegociacionesExcelDto", headerRow: 4 } };
        $(document).ready(function () { const app = $("#renegociacionesApp"); configuraciones.servidor.userEmail = app.data("user-email"); configuraciones.servidor.serverPath = app.data("server-path"); configuraciones.servidor.maxFileSize = app.data("max-file-size"); configuraciones.carga.selector = app.data("upload-selector"); $("#btnStartImport").prop("disabled", true).on("click", function (event) { event.preventDefault(); if (typeof CheckExcelFileRenegociaciones === "function") CheckExcelFileRenegociaciones(); }); });
    </script>
    <script src="../js/sharedMejorado.js?v=1"></script><script src="../js/RenegociacionesCptReNegocia.js?v=1"></script>
</asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div id="renegociacionesApp" data-user-email="<%= CType(Session.Item("User"), ICMTools.User).Email %>" data-server-path="<%= Page.Server.MapPath("~").Replace("\", "\\") %>" data-max-file-size="<%= ConfigurationManager.AppSettings("maxFileSize") %>" data-upload-selector="#<%= FileUploader.ClientID %>">
 <div class="container"><div class="row"><div class="col-12"><div class="card bg-light card-danger">
  <div class="card-header lead">Seleccione filtros y archivo a cargar</div><div class="card-body"><form id="myForm" runat="server"><div class="row"><div class="col-md-7">
   <div class="row form-group"><label class="control-label col-sm-5 text-right" for="SelectPeriod">Periodo</label><div class="col-sm-7"><asp:DropDownList ID="SelectPeriod" runat="server" ClientIDMode="Static" Enabled="false" CssClass="form-control form-control-sm"></asp:DropDownList></div></div>
   <div class="row form-group"><label class="control-label col-sm-5 text-right" for="SelectRegion">Regi&oacute;n</label><div class="col-sm-7"><asp:DropDownList ID="SelectRegion" runat="server" ClientIDMode="Static" Enabled="true" CssClass="form-control form-control-sm"></asp:DropDownList></div></div>
  </div><div class="col-md-5"><div class="form-group"><label class="control-label col-sm-12">Archivo de Renegociaciones</label><div class="col"><asp:ScriptManager ID="ScriptManager1" runat="server" /><div class="upload-drop-zone" id="drop-zone"><ajaxToolkit:AsyncFileUpload ID="FileUploader" runat="server" ThrobberID="myThrobber" OnClientUploadComplete="uploadComplete" OnClientUploadError="uploadError" OnClientUploadStarted="beforeUploadStarts" Width="100%" ErrorBackColor="#FFCCFF" CompleteBackColor="#CCFFCC" ForeColor="Black" /></div><asp:Label runat="server" ID="myThrobber" Style="display: none;"><i class="fas fa-sync-alt fa-spin fa-fw"></i>Cargando archivo...</asp:Label><div class="table-responsive"><table id="statusUploadTable" class="table table-bordered table-sm"></table></div></div></div></div></div></form></div>
  <div class="card-footer"><div class="row"><div class="col"><div id="progressDiv" class="progress" style="display: none; height: 31px;"><div id="progressBar" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"><span class="sr-only">0%</span></div></div></div><div class="col-5"><button id="btnStartImport" class="btn btn-sm btn-primary float-right" title="Iniciar importación de renegociaciones"><i class="fas fa-upload fa-fw"></i>Iniciar Importación</button><a href="../TemplateFiles/ICMToolsPlantilla_Renegociaciones.xlsx" class="btn btn-sm btn-primary float-right mr-2" title="Descargar plantilla"><i class="fas fa-download fa-fw"></i>Descargar Plantilla</a></div></div></div>
 </div></div><div class="col-12 mt-2"><div id="statusAlert" class="alert alert-warning fade" role="alert"><i class="fas fa-exclamation-triangle fa-fw"></i><strong>Importante:</strong> Espere por favor, no actualice la página.</div></div><div class="col-12" style="margin-top: -8px;"><div id="errorPanel" class="RespuestaPanel card border-danger" style="display: none;"><div class="card-header text-danger lead">Detalle de problemas</div><div class="card-body"><p id="MensajeError">Ajuste el archivo de acuerdo con los problemas detectados y vuelva a intentar.</p><div id="formatErrors" class="pt-3 table-responsive text-default"></div></div></div><div id="successPanel" class="RespuestaPanel card border-success" style="display: none;"><div class="card-header text-success lead">Carga exitosa de Renegociaciones</div><div class="card-body"><div id="formatSuccess" class="pt-3 table-responsive text-default"></div></div></div></div></div></div>
</div><script src="../vendor/bootstrap-4.1.0/dist/js/bootstrap.min.js"></script><script src="../vendor/bootstrap-filestyle-2.1.0/src/bootstrap-filestyle.min.js"></script>
</asp:Content>
